name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Heyo! Thank you for creating this issue, I'll try my best to take a look at it asap!"
        pr-message: "Thank you very much for the PR, as soon as I have the time, I'll take a look on it!"
